import ast
import copy
import datetime
import os
import re
import sys
import uuid

# Ensure repository root is on sys.path so `src` package imports work during tests
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

try:
    import dotenv  # type: ignore
except Exception:  # pragma: no cover - optional test dependency
    import types

    dotenv = types.SimpleNamespace(load_dotenv=lambda *a, **k: None)
    sys.modules["dotenv"] = dotenv

import pytest
try:
    import psycopg
except Exception:  # pragma: no cover - optional test dependency
    psycopg = None
try:
    from langchain_core.messages import HumanMessage
except Exception:  # pragma: no cover - optional test dependency
    class HumanMessage:
        def __init__(self, content: str):
            self.content = content

from src.config import config
from src.schemas import (
    SemanticMemoryStagerSnapShot,
    SemanticBufferConsolidatorState,
    MemoryBatch,
    MemoryRecord,
    AdjudicatedMemoryItem,
    AdjudicatedMemoryList,
)
from src.consolidation import adjudication, bitemporal_split

import src.memory as src_memory


@pytest.fixture(scope="session", autouse=True)
def initialize_database():
    # Schema initialization happens inside the `db_conn` fixture after the
    # transactional test connection is provided and monkeypatched into modules.
    yield


@pytest.fixture
def db_conn(monkeypatch):
    db_url = os.environ.get("DB_URL", config.DB_URL)
    conn = psycopg.connect(db_url, autocommit=False)
    # Prevent node-level commits from breaking transactional rollback.
    def noop_commit():
        return None

    monkeypatch.setattr(conn, "commit", noop_commit)

    import src.memory as src_memory
    monkeypatch.setattr(src_memory, "conn", conn)
    monkeypatch.setattr(adjudication, "conn", conn)
    monkeypatch.setattr(bitemporal_split, "conn", conn)
    import src.writeside.semantic_buffer_writer
    monkeypatch.setattr(sys.modules["src.writeside.semantic_buffer_writer"], "conn", conn)
    # Now that the package-level connection has been set, initialize schemas
    # using the same transactional connection so tests operate in a rollbackable
    # transaction.
    src_memory.initialize_db()
    yield conn
    conn.rollback()
    conn.close()


@pytest.fixture
def base_snapshot():
    return SemanticMemoryStagerSnapShot(
        run_id=uuid.uuid4(),
        user_id=str(uuid.uuid4()),
        conversation_id="test-conversation",
        message_id="test-message",
        message_timestamp=datetime.datetime.utcnow(),
        latest_message=[HumanMessage(content="test message")],
    )


@pytest.fixture
def base_state(base_snapshot):
    return {
        "snapshot": base_snapshot,
        "semantic_memories_processed": MemoryBatch(memmories=[]),
        "fresh_memories": MemoryBatch(memmories=[]),
        "adjudicated_memories": AdjudicatedMemoryList(memories=[]),
    }


def _normalize_textual_batch(content: str) -> list[dict]:
    # The human content embeds Python reprs with UUID and datetime objects.
    text = content.split("Adjudicate the following memory candidates.", 1)[-1]
    text = text.strip()
    text = re.sub(r"UUID\('([0-9a-fA-F-]+)'\)", r"'\1'", text)

    def _datetime_repl(match):
        parts = [int(p.strip()) for p in match.group(1).split(",")[:6]]
        dt = datetime.datetime(*parts)
        return repr(dt.isoformat())

    text = re.sub(r"datetime\.datetime\(([^)]*)\)", _datetime_repl, text)
    return ast.literal_eval(text)


class FakeLLM:
    def invoke(self, messages):
        human = next(m for m in messages if isinstance(m, HumanMessage))
        candidates = _normalize_textual_batch(human.content)
        memories = []
        for candidate in candidates:
            new_memory = candidate["new_memory"]
            existing = candidate["existing_memories"]
            action = "ADD"
            target_fact_ids = []
            if existing:
                if any(row["object"] == new_memory["object"] for row in existing):
                    action = "IGNORE"
                    target_fact_ids = [row["fact_id"] for row in existing if row["object"] == new_memory["object"]]
                elif len(existing) == 1:
                    action = "REPLACE"
                    target_fact_ids = [row["fact_id"] for row in existing]
                else:
                    action = "CONTRADICT"
                    target_fact_ids = [row["fact_id"] for row in existing]
            memories.append(
                AdjudicatedMemoryItem(
                    memory=MemoryRecord.model_validate(new_memory),
                    action=action,
                    target_fact_ids=target_fact_ids,
                    adjudication_reason=f"{action} generated by fake LLM",
                )
            )
        return AdjudicatedMemoryList(memories=memories)


@pytest.fixture(autouse=True)
def fake_external_services(monkeypatch):
    monkeypatch.setattr(adjudication, "structured_llm", FakeLLM())
    monkeypatch.setattr(bitemporal_split, "embed_text", lambda text: [0.0] * 1536)
    yield


@pytest.fixture
def pipeline_graph():
    from langgraph.graph import StateGraph, START, END

    graph = StateGraph(SemanticBufferConsolidatorState)
    graph.add_node("AG", adjudication.ajudication_gate)
    graph.add_node("FM", bitemporal_split.consolidate_fresh_memories)
    graph.add_node("BS", bitemporal_split.bitemporal_split)
    graph.add_edge(START, "AG")
    graph.add_edge("AG", "FM")
    graph.add_edge("FM", "BS")
    graph.add_edge("BS", END)
    return graph.compile()


@pytest.fixture
def pipeline_state_snapshot():
    recorded = []

    def wrapper(func, name):
        def wrapped(state):
            before = copy.deepcopy(state)
            result = func(state)
            after = copy.deepcopy(result)
            recorded.append((name, before, after))
            return result

        return wrapped

    yield recorded, wrapper
