
SEMANTIC_TOP_K = 10
EPISODIC_TOP_K = 5

MAX_FUSED_RESULTS = 10

SEMANTIC_BUDGET_RATIO = 0.60
EPISODIC_BUDGET_RATIO = 0.40


MAX_CONTEXT_TOKENS = 2000
CONTEXT_TOKEN_BUDGET = MAX_CONTEXT_TOKENS

SEMANTIC_TOP_K
EPISODIC_TOP_K
MAX_FUSED_RESULTS
SEMANTIC_BUDGET_RATIO
EPISODIC_BUDGET_RATIO
